In [ ]:
# 정식일 이후 16주 동안 단위면적당 최소 에너지 비용(누적 난반용 도시가스 사용량)으로 최대 수확량을 예측 할 수 있는 환경/생육 모델을 구해라

In [1]:
import pandas as pd
import numpy as np

In [2]:
input_data = pd.read_csv('2023_smartFarm_AI_hackathon_dataset.csv')
input_data

,frmDist,date,inTp,inHd,otmsuplyqy,acSlrdQy,cunt,ph,outTp,outWs,...,outtrn_cumsum,WaterUsage,WaterCost,FertilizerUsage,FertilizerCost,CO2Usage,CO2Cost,MistUsageTime,Mist Cost,HeatingEnergyUsage_cumsum
0,DBSF1059,20220926,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.0
1,DBSF1059,20221001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,1347.554178,202.133127,4711.308821,5936.249114,0.000000,0.0000,190.168990,2221.173803,0.0
2,DBSF1059,20221002,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,69.899353,10.484903,271.379890,341.938662,0.000000,0.0000,0.000000,0.000000,0.0
3,DBSF1059,20221003,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,412.225065,61.833760,1539.505534,1939.776973,253.744916,149.7095,0.000000,0.000000,0.0
4,DBSF1059,20221004,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,590.608634,88.591295,2614.973165,3294.866187,3032.885084,1789.4022,1.149739,13.428955,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84835,DBSF9969,20180710,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,235272.042536,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.0
84836,DBSF9969,20180711,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,227947.124946,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.0
84837,DBSF9969,20180712,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,231527.426327,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.0
84838,DBSF9969,20180713,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,251254.321635,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.0
84839,DBSF9969,20180714,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.0

In [3]:
input_data.columns

Index(['frmDist', 'date', 'inTp', 'inHd', 'otmsuplyqy', 'acSlrdQy', 'cunt',
       'ph', 'outTp', 'outWs', 'daysuplyqy', 'inCo2', 'ec', 'frmYear',
       'frmWeek', 'frtstGrupp', 'lefstalklt', 'frtstSetCo', 'pllnLt',
       'flanGrupp', 'frtstCo', 'flanJnt', 'tcdmt', 'frmhsFclu', 'hvstGrupp',
       'hvstJnt', 'grwtLt', 'fcluHg', 'lefLt', 'flwrCo', 'hvstCo', 'lefCunt',
       'frtstJnt', 'lefBt', 'stemThck', 'frmAr', 'frmDov', 'outtrn_cumsum',
       'WaterUsage', 'WaterCost', 'FertilizerUsage', 'FertilizerCost',
       'CO2Usage', 'CO2Cost', 'MistUsageTime', 'Mist Cost',
       'HeatingEnergyUsage_cumsum'],
      dtype='object')

In [4]:
input_data.describe()

,date,inTp,inHd,otmsuplyqy,acSlrdQy,cunt,ph,outTp,outWs,daysuplyqy,...,outtrn_cumsum,WaterUsage,WaterCost,FertilizerUsage,FertilizerCost,CO2Usage,CO2Cost,MistUsageTime,Mist Cost,HeatingEnergyUsage_cumsum
count,8.484000e+04,84840.000000,84840.000000,84840.000000,84840.000000,84840.000000,84840.000000,84840.000000,84840.000000,84840.0,...,84840.000000,84840.00000,84840.000000,84840.000000,84840.000000,84840.000000,84840.000000,84840.000000,84840.000000,8.484000e+04
mean,2.018306e+07,16.741165,69.840334,63.771906,859.358175,11.050016,4.329564,8.919073,0.507100,0.0,...,24128.137397,154.82117,23.223176,381.415436,480.583450,13.142900,7.754311,10.462087,122.197176,1.369699e+05
std,1.415661e+04,7.844482,30.632917,50.989079,863.627104,13.169075,2.360309,9.562816,0.736510,0.0,...,38713.785840,514.61495,77.192242,1265.736256,1594.827682,227.353742,134.138708,59.149613,690.867475,5.413194e+05
min,2.017071e+07,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-15.832372,0.000000,0.0,...,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00
25%,2.017121e+07,15.181276,67.966019,0.000000,0.000000,1.663457,4.428794,0.000000,0.000000,0.0,...,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00
50%,2.018041e+07,18.164113,78.384204,67.951238,762.690836,7.087341,5.208487,7.014140,0.000000,0.0,...,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00
75%,2.018120e+07,21.158215,88.724599,91.599089,1477.986231,15.514866,5.917302,17.122196,0.862444,0.0,...,40064.347955,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00
max,2.022121e+07,39.221978,119.051100,335.648934,4422.127255,100.947446,8.126081,36.776236,6.497037,0.0,...,253678.264188,5388.27699,808.241549,10440.000887,13154.401118,8387.322508,4948.520280,838.686300,9795.855985,4.031464e+06

In [7]:
X = input_data.drop(columns=['outtrn_cumsum', 'HeatingEnergyUsage_cumsum', 'frmDist'])
Y = input_data[['outtrn_cumsum', 'HeatingEnergyUsage_cumsum']]

In [8]:
print(X.shape)
print(Y.shape)

(84840, 44)
(84840, 2)

In [9]:
from sklearn.model_selection import train_test_split
train_input, test_input, train_target, test_target = train_test_split(
    X, Y, test_size=0.2, random_state=42
)

In [10]:
print(train_input.shape, test_input.shape)
print(train_target.shape, test_target.shape)

(67872, 44) (16968, 44)
(67872, 2) (16968, 2)

In [11]:
# 정규화
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(train_input)
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)

In [16]:
# from sklearn.linear_model import LinearRegression
# model = LinearRegression()
# model.fit(train_scaled, train_target)

# 라쏘 회귀 모델 생성
from sklearn.linear_model import Lasso
alpha = 0.01  # 라쏘 회귀의 alpha 값 설정
lasso_model = Lasso(alpha=alpha)

# 모델 학습
lasso_model.fit(train_scaled, train_target)

Lasso(alpha=0.01)

In [18]:
y_pred = lasso_model.predict(test_scaled)
y_pred

array([[  15225.2634358 ,  112139.05747736],
       [  23329.24909788,  -75030.33106544],
       [  16503.37670451,   -3389.31655269],
       ...,
       [  -8738.5517351 , 1531011.72346587],
       [  29253.07540993,  -64779.35055237],
       [  16064.06356655,  936548.565085  ]])

In [20]:
from sklearn.metrics import mean_squared_error, r2_score
from math import sqrt

rmse = sqrt(mean_squared_error(test_target, y_pred))
r2score = r2_score(test_target, y_pred)

print(f'RMSE: {rmse}')
print(f'R2 Score: {r2score}')

RMSE: 237572.81596802466
R2 Score: 0.5249293017175084